DROP TABLE IF EXISTS users, items, bookings, requests, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(250) NOT NULL,
  email varchar(250) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description varchar(500) NOT NULL,
  requester_id bigint NOT NULL REFERENCES users(id),
  created timestamp NOT NULL,
  CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner_id bigint NOT NULL REFERENCES users(id),
  request_id bigint REFERENCES requests(id),
  name varchar(100) NOT NULL,
  description varchar(500) NOT NULL,
  is_available bool NOT NULL,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  status varchar(10) NOT NULL,
  start_date timestamp without time zone NOT NULL,
  end_date timestamp without time zone NOT NULL,
  item_id bigint NOT NULL REFERENCES items(id),
  booker_id bigint NOT NULL REFERENCES users(id),
  CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text varchar(1000),
  item_id bigint NOT NULL REFERENCES items(id),
  author_id bigint NOT NULL REFERENCES users(id),
  created timestamp without time zone NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id)
);